// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy73Vfw7ZaaesD-cQlLgyW0ygd_1A4NyY',
    appId: '1:1026332641008:web:8570de76cd2e41a35c6435',
    messagingSenderId: '1026332641008',
    projectId: 'fir-project-6fb5e',
    authDomain: 'fir-project-6fb5e.firebaseapp.com',
    storageBucket: 'fir-project-6fb5e.appspot.com',
    measurementId: 'G-ST01XMGPCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CxIjHNsiKeUUzoVChn_VJduvDJt7AWA',
    appId: '1:1026332641008:android:176a3008b5b50a935c6435',
    messagingSenderId: '1026332641008',
    projectId: 'fir-project-6fb5e',
    storageBucket: 'fir-project-6fb5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1aLNLrRqqoIEntznrXXfvanvr7vN3Mxk',
    appId: '1:1026332641008:ios:cb7334f1a1dfcb615c6435',
    messagingSenderId: '1026332641008',
    projectId: 'fir-project-6fb5e',
    storageBucket: 'fir-project-6fb5e.appspot.com',
    iosBundleId: 'com.example.firebaseProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1aLNLrRqqoIEntznrXXfvanvr7vN3Mxk',
    appId: '1:1026332641008:ios:3b30c155663c4fcc5c6435',
    messagingSenderId: '1026332641008',
    projectId: 'fir-project-6fb5e',
    storageBucket: 'fir-project-6fb5e.appspot.com',
    iosBundleId: 'com.example.firebaseProj.RunnerTests',
  );
}
