// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KZ4LPnjUP0akYDzEIPz3gt_XtYO4gmY',
    appId: '1:342259365894:web:9f1cbf27780766e2c8eb87',
    messagingSenderId: '342259365894',
    projectId: 'practice-project-e75c8',
    authDomain: 'practice-project-e75c8.firebaseapp.com',
    storageBucket: 'practice-project-e75c8.appspot.com',
    measurementId: 'G-YMDWGT6Y0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD81gBbNRLpdqn1-FjshZQPyg-1SF09tM',
    appId: '1:342259365894:android:92aa629b0acdb54ec8eb87',
    messagingSenderId: '342259365894',
    projectId: 'practice-project-e75c8',
    storageBucket: 'practice-project-e75c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWwHebfRU-2gcixwS9ceuzSt_JJfqolJc',
    appId: '1:342259365894:ios:c17e431679151b8ac8eb87',
    messagingSenderId: '342259365894',
    projectId: 'practice-project-e75c8',
    storageBucket: 'practice-project-e75c8.appspot.com',
    iosBundleId: 'com.example.testStyling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWwHebfRU-2gcixwS9ceuzSt_JJfqolJc',
    appId: '1:342259365894:ios:9dac412dd616d775c8eb87',
    messagingSenderId: '342259365894',
    projectId: 'practice-project-e75c8',
    storageBucket: 'practice-project-e75c8.appspot.com',
    iosBundleId: 'com.example.testStyling.RunnerTests',
  );
}
